version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sg_blog
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis 缓存
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 后端服务（Spring Boot）
  backend:
    build:
      context: ./sangeng-blog
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sg_blog
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_REDIS_HOST: redis
    depends_on:
      - mysql
      - redis

  # 前端服务（Vue）
  frontend:
    build:
      context: ./sgblog-front-end/sg-blog-vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      VUE_APP_API_URL: http://backend:7777
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
